#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Apr 30, 2026 11:06:29 AM EEST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

#import unknown_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black'
_tabfg2 = 'white'
_bgmode = 'light'
_tabbg1 = '#d9d9d9'
_tabbg2 = 'gray40'

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return
    try: unknown_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+340+191")
        top.minsize(1, 1)
        top.maxsize(1265, 994)
        top.resizable(1,  1)
        top.title("Toplevel 0")

        self.top = top

        _style_code()
        self.TProgressbar1 = ttk.Progressbar(self.top)
        self.TProgressbar1.place(relx=0.183, rely=0.156, relwidth=0.5
                , relheight=0.0, height=19)
        self.TProgressbar1.configure(length="300")
        self.TProgressbar1.configure(value='90')

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.183, rely=0.333, height=29, width=63)
        self.Button1.configure(activebackground="#5b25d8")
        self.Button1.configure(background="#2dd872")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#1822a3")
        self.Button1.configure(text='''Ok''')

root = tk.Tk()
Toplevel1(root)
tk.mainloop()



